import verifiedEditions from "./trailer-editions.generated.json";

export type TrailerEdition = {
  id: string;
  brand: string;
  style: string;
  title: string;
  seconds: number;
  description: string;
  video: string;
  poster: string;
  captions: string;
  transcript: string;
  proof: string;
  master: string;
  sha256: string;
};

/** Generated by scripts/sync-trailer-editions.py from full-decode receipts. */
export const trailerEditions: readonly TrailerEdition[] = verifiedEditions;
