import { createFileRoute } from "@tanstack/react-router";
import { QuasarSites } from "@/components/quasar/sites";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/quasar/sites")({
  // The Quasar service is reached from the browser, never from this server.
  ssr: false,
  head: () =>
    pageHead(
      "Sites — Quasar",
      "Sites generated by your local Quasar service, read live from your browser.",
    ),
  component: QuasarSites,
});
