# Abbey CLI / TUI

<!-- BEGIN abbey-generated:claims-summary -->
<!-- Generated by tools/check_claims_sync.py; do not edit. -->
Canonical capability ledger: **40 Current · 3 Partial · 8 Proposed · 1 Blocked · 5 Out of scope** ([full evidence](docs/claims.md)). Source: `src/claims.rs`; schema 2; digest `6a5150ae646a3ed49a7e97722a5c177dbb95a82dd74166e6d4139391c9499817`.
Executable workflow ledger: **27 goals (24 done, 1 in_progress, 1 proposed, 1 blocked) · 168 checked / 25 open todos** (stable goal metadata in `tasks/goals.md`).
<!-- END abbey-generated:claims-summary -->

> **Intelligence Without Limits — with a claims ledger.**  
> Hybrid CLI/TUI companion for coding and ops: personas, skills, parallel peers,  
> and verbs that refuse what isn’t **Current**.

abi is the runtime/WDBX; Abbey is the companion that will not claim what the ledger cannot prove. See [docs/brand.md](docs/brand.md).

**v2.6** — production-structured hybrid CLI/TUI (modular `src/`, `./check.sh` gate).

Personas · Max/Gemma · parallel · OS control · skills/plugins · self-learn · unique build stamp.

Docs: [identity](docs/identity.md) · [architecture](docs/architecture.md) · [production](docs/production.md).

| Target CLI | Abbey surface |
|------------|----------------|
| **Grok Build** | TUI default, `-c/--continue`, `-w/--worktree`, `--cwd`, model aliases, session resume |
| **Codex** | `exec`/`print`, `review`, `doctor`, `login`/`logout`, `mcp`/`plugin`, `completion`, sandbox/force |
| **Claude Code** | slash commands (`/plan`, `/diff`, `/pr`, `/init`, `/commit`, `/clear`…), `-p`, ask/plan modes |

## Install

```bash
cd ~/dev/active/abbey
./install.sh
# or:
cargo build --release
./install.sh          # Unix/macOS → ~/.local/bin/abbey + abbeyd
# Windows:  powershell -File .\install.ps1  → %LOCALAPPDATA%\abbey\bin\abbey.exe
# Both installers name what they install after the compiled edition
# (src/edition.rs), so the two editions never overwrite each other:
#   ABBEY_CARGO_FEATURES=personal-edition → abbey-personal / abbey-personal.exe
# install.sh is executed and verified here; install.ps1's naming is proved only
# by a parser test — no Windows host has run it (Partial, see docs/claims.md).
```

Requires the exact **Rust nightly-2026-09-01** toolchain (`rustc 1.100.0-nightly`)
from `rust-toolchain.toml`, using Rust edition 2024. Generation commands require an
executor; local verbs (claims, memory/inventory, os, doctor, mesh, daemon-client,
installer probes) run with none installed. `ollama` is the preferred default
(local `gemma4:26b-mlx`, alias `gemma:27b-mlx`); when it is absent the unchosen
default falls back to the first installed of `grok`, `fm`, `abi`, `claude`, then
`cursor-agent` last (doctor shows the automatic choice), and `ABBEY_BACKEND` still
selects one explicitly. No single backend is a hard requirement.

## Quick use

```bash
abbey                     # TUI
abbey "fix the flaky test"
abbey -c                  # continue session
abbey -m fable plan "…"
abbey exec "summarize src/"
abbey review
abbey security-review
abbey commit
abbey pr
abbey init                # scan cwd → AGENTS.md
abbey init --force        # overwrite
abbey init --print        # preview only
abbey init --agent        # local scan, then refine with cursor-agent
abbey doctor
abbey daemon status                          # authenticated local read-only query
abbey daemon status --json                   # typed AppEvent JSON
abbey daemon claims --status proposed
abbey daemon claims --contains desktop --json
abbey daemon negotiate --json                # explicit protocol-v3 read_models grant
abbey daemon models                          # bounded startup-owned model inventory
abbey claims                                 # Current / Partial / Proposed / Blocked / OOS
abbey claims proposed                        # approved but not implemented roadmap
abbey claims blocked                         # externally blocked runtime/proof work
abbey claims refuse lora                     # honest exit 2
abbey platform                               # linux/macos/windows matrix + threads
abbey compute                                # GPU/NPU/TPU host detect (not Abbey kernels)
abbey vision                                 # path attach + agent gen (local neural models Proposed)
abbey cot show                               # last reason transcript (not Abbey CoT engine)
abbey runtime                                # who runs tools (owned host is Proposed)
abbey oos                                    # shipped-edition bypass · fake cost · vendor runtimes
abbey lora|weights|accel|shell|host          # per-topic status / refuse (exit 2)
abbey hybrid-loop "add a dark mode toggle"   # Gemma interprets → Max implements
abbey subagents                              # catalog (abbey lanes + PATH peers)
abbey subagents run --lanes max,reviewer --synthesize "harden auth"
abbey parallel --peers gemini,claude "second opinions"   # local distributed peers
abbey routes --correlation <id>              # both stages (conf · alt · fb)
abbey learn review                           # train_candidate provenance curation
abbey learn stats
abbey learn improve [n] [--apply]            # propose from routes/reflect; --apply promotes routes only
abbey learn-review · abbey learn-stats       # aliases
abbey os · abbey allowlist                   # allowlist panel (execute needs --confirm)
abbey wdbx query                             # → `abi wdbx query <abbey store> --json`
abbey wdbx stats                             # in-process (needs --features wdbx)
abbey mesh local-demo --nodes 3 --json       # authenticated Unix same-host ABI process proof
abbey completion zsh > ~/.zsh/completions/_abbey_clap
```

### Authenticated application daemon

Abbey ships a narrow `abbeyd` runtime on Unix. Protocol v1 preserves the exact
`status` and `claims` read contracts; protocol v2 adds durable submit/status/cancel/event
pages only for startup-bound ABI-local and Foundation Models recipes over the same
length-prefixed owner-only Unix socket. Requests cannot choose a program, argv,
environment, workspace, tool, or shell. Protocol v3 uses a separate strict envelope. It
supports bounded fixed-watermark inventory from the same structurally read-only three-tool
registry used by MCP. The default safe daemon appends one local-only mutating descriptor,
`abbey_memory_mark_obsolete`; invoking it validates one opaque record ID, persists only an
exact call digest with a bounded expiry, and returns a typed pending-approval status without
executing or storing raw input. The personal build and MCP retain only the three read-only
tools. Protocol v3 also supports exact stable-ID claim lookup from the canonical registry. It
additionally negotiates `read_models` when an ABI-local provider was bound at daemon
startup; `ListModels` combines that provider inventory with any edition-scoped
`*_MODEL_MANIFEST_DIR` presence catalog and signed `*_MODEL_RUNTIME_CONFIG` lifecycle
catalog. Route entries remain first, and the catalog is frozen at startup. Missing or
non-exact claim IDs return `not_found`, and fuzzy claim search remains unavailable. The
canonical read-only tools can also be invoked through the typed v3 client after schema and
policy validation. Schema v5 owns the pending digest and append-only transitions, but
exact approve/deny/cancel plus schema-v6 approved resubmission are also served for the one
safe-edition mutation. Schema-v7 signed lifecycle authority can additionally grant exact
download/load/unload and status operations; it does not add prompt inference or a
global/default route. Every other unserved v3 grant remains denied. Create a private
bearer file and start it explicitly:

```bash
umask 077
mkdir -p "${XDG_STATE_HOME:-$HOME/.local/state}/abbey/daemon"
openssl rand -hex 32 > "${XDG_STATE_HOME:-$HOME/.local/state}/abbey/daemon/bearer"
ABBEYD_BEARER_TOKEN_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/abbey/daemon/bearer" abbeyd

# In a second shell, use the same socket and exactly one bearer source:
ABBEYD_BEARER_TOKEN_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/abbey/daemon/bearer" \
  abbey daemon status
abbey daemon run submit --backend abi --json -- 'bounded input'
abbey daemon negotiate --json
abbey daemon models --limit 32 --json
```

The socket defaults to `<state>/daemon/abbeyd.sock`. `--json` emits the typed
`AppEvent` or `V3Event`, not the transport envelope. The v3 model commands make one
explicit negotiation and one bounded inventory read, echo the exact negotiated grant,
and never downgrade or retry. These commands neither resolve nor contact a
model executor and never fall back to an in-process answer after connection or
authentication failure. Windows reports the named-pipe transport as unsupported until
that transport and runtime proof exist. Startup also performs the bounded backup-first
legacy conversation metadata migration documented in `docs/runtime.md`; it does not
import transcripts or memory. Separately, normal Unix identity saves and clears commit
opaque edition-scoped evidence or explicit tombstones before an owner-only recovery
journal creates or removes exact compatibility mirrors. Clear retains history,
transcripts, memory, models, route/run data, and finalized backups. Reads recover that
journal, select cwd before global from canonical edition-scoped evidence, honor
tombstones, and accept a selected mirror only when its external identity matches the
canonical digest; corrupt selected state fails closed. Untracked scopes retain bounded
legacy compatibility. This coordinator adds no daemon command or protocol and is not the
Proposed provider-neutral Abbey-owned agent/tool runtime.

### Slash (CLI or TUI prompt)

```text
/help  /plan  /ask  /diff  /review  /security-review
/commit  /pr  /init [--force|--print|--agent]  /branch name
/clear  /compact  /model fable  /memory  /routes  /skills  /permissions  /doctor
/learn correction|preference|routes|digest|review|stats|improve
```

## Backends

| Backend | `ABBEY_BACKEND` | Notes |
|---|---|---|
| cursor-agent | `cursor` (default) | hosted models, full tool surface |
| Grok Build | `grok` | passthrough |
| **On-device** | `fm` | Apple Foundation Models CLI, **macOS 26+** — no cursor-agent, no network |
| **abi** | `abi` | sibling `abi` CLI (`abi complete`) — **no cursor-agent required**; local persona-template by default, `claude-*`/`live` opt into abi's Anthropic transport |
| **Claude Code** | `claude` | isolated Claude argv + native session resume; requires the `claude` CLI and its own account/plan; live provider behavior is not claimed by the source tests |

```bash
ABBEY_BACKEND=fm abbey -p "summarise this error"     # runs on-device
ABBEY_BACKEND=fm abbey doctor                        # reports model availability
ABBEY_BACKEND=abi abbey -p "hello"                   # through the abi CLI (no cursor-agent)
ABBEY_BACKEND=abi abbey                              # full TUI on abi; Ctrl-B cycles backends
ABBEY_BACKEND=claude abbey -p "hello"                # through Claude Code (no cursor-agent)
```

Make a backend the persistent default with `backend = "abi"` in
`~/.config/abbey/config.toml` (`ABBEY_BACKEND` still wins when set). Run
`abbey config --init` to scaffold an annotated config with every key commented;
it never overwrites an existing file, and an unrecognised `backend` value warns
rather than silently falling back to cursor-agent.

Under `fm`, conversations are kept as transcript files in `<state>/fm/` (it has no
server-side chat ids), and `ask`/`plan` become `--instructions`. Account/session verbs
(`status`, `ls`, `login`, `logout`) have no on-device equivalent and refuse with exit 2
rather than forwarding; local `mcp status|paths|view` remains available and management
names its provider explicitly. **Max and Gemma both resolve to the `system` model there,
so the role distinction is carried by the prompt, not the model.**

Under `abi`, each turn is a one-shot `abi complete` (needs a **real** `abi` binary —
`ABBEY_ABI_BIN` or `abi_bin`; a shell alias won't do). Abbey keeps continuity itself:
turns are recorded in `<state>/abi/<chat>.transcript` and a bounded tail rides into the
next turn as context. Account/generation verbs refuse with exit 2; local MCP inventory is
backend-independent and provider management is explicit. Roles are prompt-only, and cursor
role/thinking bindings never silently select the live transport.

Under `claude`, Abbey builds Claude's argv from scratch, maps its model aliases onto
Claude's vocabulary, and uses Claude's own session store. Abbey writes only a local
presence marker after a successful first turn so the next call uses `--resume` instead
of reusing `--session-id`. These wiring and argv boundaries are deterministic-test
evidence; this repository has not established live account, plan, catalog, or response
quality claims.

## The 3-D memory map

Every memory has a position on three interpretable axes — **topic** (subject tag),
**recency** (log-compressed age), **consolidation** (activity → stm → ltm →
train_candidate, lifted by confidence):

```bash
abbey memory put "plays fingerstyle guitar" --tag guitar --retention ltm
abbey memory map                 # the whole map
abbey memory near <id>           # what else do I know about this?
```

When something you stored turns out to be wrong, retire it rather than deleting it —
memories are never silently removed, so the provenance trail survives:

```bash
abbey memory invalidate <id>                     # mark obsolete, keep the record
abbey memory supersede <old-id> "corrected fact" # store the fix, retire the old
```

Tag your memories — untagged ones share one visible `(untagged)` column. Both backends
compute these coordinates from the stored record; WDBX uses KV JSON for the memory record
and does not create a second spatial copy.

This map is a **deterministic layout, not a learned embedding space**. Learned semantic
search is a separate, explicit provider/index surface; map distance must not be described
as semantic distance. The TUI Memory tab shows a short map preview; use the CLI for the
full map.

## Semantic memory (opt-in)

Semantic embeddings are disabled by default. Select exactly one provider in the generated
config (`abbey config --init`) or with environment overrides; Abbey never falls back from
Apple to a remote endpoint or vice versa:

```toml
[embeddings]
provider = "apple"                  # none | apple | openai
model = "english-sentence"
dimension = 512
language = "en"
```

```bash
abbey memory embed status
abbey memory embed --all             # explicit non-destructive backfill
abbey memory semantic "brief terminal responses" --project "$PWD" --limit 10
```

The Apple provider uses the OS `NaturalLanguage.NLEmbedding` sentence space. The
OpenAI-compatible provider calls `/v1/embeddings` with bounded batches and HTTPS (plain
HTTP is accepted only for loopback tests); its key comes only from
`ABBEY_EMBEDDING_API_KEY` or `OPENAI_API_KEY`. Only summary plus subject tags leave the
process—never payload, provenance, project, or source references. SQLite persists vectors
in `memory_embeddings`; WDBX uses an isolated v2 vector sub-store per provider/model/
revision/dimension/normalization `space_id`. Provider failures preserve the memory and
leave it pending for a later explicit backfill.

## Routing audit

`abbey routes` / `/routes` print persona, role, model, **confidence**, stage,
**alternate**, and **fallback**. These fields are audit-only — Abbey does not
auto-run a second agent when confidence is low. Prefer `hybrid-loop` or `/gemma`
when the alternate is Gemma.

## Media, thinking, generation, and tools

Abbey does **not** embed pixels or ship local vision/generation weights. Attach and
generate both go through **cursor-agent** (and any MCP image/video tools it has):

```bash
# Attach (read)
abbey --image ./shot.png "what is wrong with this UI?"
abbey /image ./shot.png describe the layout

# Generate (write via agent tools)
abbey imagine "a fox reading in a candlelit library" --aspect 16:9 --out ./fox.png
abbey imagine --edit ./fox.png "make it dawn" --out ./fox-dawn.png
abbey generate video "short timelapse of a city skyline" --out ./sky.mp4
abbey /imagine --out=./mark.png abbey logo mark, simple

# Reason (Cursor thinking model + structured wrap)
abbey reason "should we split session.rs further?"
abbey --thinking xhigh "…"
abbey /reason compare sqlite vs wdbx for this workload

# MCP / ACP
abbey mcp                  # inventory ~/.cursor/mcp.json + project configs
abbey mcp paths
abbey mcp view codex       # structured provider view
abbey mcp cursor list      # explicit provider management
abbey plugin codex list    # provider-explicit plugin management
abbey --approve-mcps "…"   # tools run inside cursor-agent during a turn
abbey acp                  # ACP peers (gemini --acp, opencode acp, …)
abbey acp run gemini       # start ACP stdio server for an ACP host to attach

# Voice (macOS — Premium/Enhanced when downloaded)
abbey voice voices
abbey speak "build finished"                 # best installed voice
abbey voice speak -v "Zoe (Premium)" -o ./note.m4a "ship it"
abbey voice listen --seconds 5               # on-device Speech STT
abbey voice ask --seconds 6                  # listen → agent → speak

# Syntax highlight (auto on -p/print/commit fences when TTY)
abbey highlight src/main.rs
abbey highlight --lang rust -
abbey -p "show me a rust hello world"   # fenced blocks colourised
ABBEY_HIGHLIGHT=0 abbey -p "…"          # disable
```

- Generation fails honestly if the agent has no image/video tool — Abbey does not fake files.
- `/think` sets a Cursor `*-thinking-*` model id; `/reason` also applies a structured reasoning wrap.
- Voice prefers **Premium → Enhanced → standard** `say` voices; download them in
  System Settings → Accessibility → Spoken Content. STT builds `scripts/abbey-stt.swift`
  on first listen (Xcode CLT + Mic + Speech Recognition permission).
- Local MCP inventory works under every generation backend; account/generation verbs still
  refuse under `ABBEY_BACKEND=fm`, and provider management is always explicit.

## Memory backends

SQLite is the default. The in-process WDBX backend (`abi-wdbx` `DurableStore`) is real but
**off by default** — it pulls a heavier dependency tree:

```bash
cargo build --features wdbx
ABBEY_MEMORY_BACKEND=wdbx abbey memory search "…"   # or memory_backend = "wdbx" in config.toml
```

`./install.sh` builds **without** the feature, so an installed `abbey` asked for `wdbx` will
fall back to SQLite — and say so in `abbey doctor`. It never silently pretends.

Concurrent `abbey` processes are safe on both backends: SQLite via its own file locking, WDBX
via an `fs4` advisory-lock guard Abbey holds for the store's lifetime — `flock(2)` on Unix,
`LockFileEx` on Windows (`abi-wdbx` itself has no cross-process locking — without the guard,
simultaneous writers corrupt the WAL beyond recovery). `abbey wdbx` passthroughs aimed at
Abbey's own store take the same lock, so the bridge can't route around it. Caveat: the guard
does not extend to an `abi` invoked directly by you against the same store.

## Honest limits

- The preferred default backend is **cursor-agent**, but it is never required: `fm`,
  `abi`, `grok`, and `claude` serve configured routes without it, and the unchosen default falls
  back to whichever of them is installed. Abbey does not reimplement Grok/Codex/Claude
  runtimes.
- `abbey wdbx <query|db|…>` shells out to `abi`, which must be a **real binary** on PATH —
  a shell alias will not do (`cargo build -p abi-cli` in `../abi`, then set `ABBEY_ABI_BIN`).
  `stats`/`checkpoint` are answered in-process and need `--features wdbx`.
- WDBX stores memory records in KV JSON and semantic vectors in a separate v2 sub-store per
  `space_id`; incompatible providers/models/dimensions are never compared.
- The WDBX cross-process lock uses `fs4` on Unix and Windows. GPU/NPU/TPU *host*
  detection is Current (`abbey platform`); Abbey accelerator runtimes are Proposed and
  remain unavailable until implementation and proof land.
- Under WDBX lock contention a run's background STM/activity write is dropped silently (it is
  best-effort by design). Explicit `abbey memory`/`abbey learn` writes surface the error.
- The TUI memory panel opens the store with a 250 ms timeout so a redraw never stalls; a
  locked store shows `unavailable: …` rather than reporting an empty store.
- Personas, Max/Gemma bindings, memory, hybrid-loop, fm, and the 3-D map are **Current** —
  local production weights and LoRA are Proposed, not implemented.
- `abbey learn review`/`stats` curate `train_candidate` provenance; they are not yet a trainer.
- `/cost` is **N/A** (use Cursor account dashboard).
- MCP/plugin management names its provider (`cursor|codex|claude`, plus `abi` for plugins);
  inventory failures and marketplace visibility are not reported as installed/runtime proof.
- Worktree isolation depends on cursor-agent `--worktree`.
- `/init` local scan covers Rust/Node/Zig/Go/Python/Swift/Make/CMake; `--agent` refines via cursor-agent.

## Layout

```
src/
  main.rs         thin entry (<200 lines)
  lib.rs          shared library boundary
  entry.rs        library-owned CLI/TUI routing
  app_core/       protocol-v1 reads + protocol-v2 runs + additive v3 contracts
  run_control.rs  shared CLI/TUI run grammar + sanitized lifecycle reducer
  bin/abbeyd.rs   bounded authenticated Unix daemon entry
  daemon/         owner-only Unix server + startup-bound run routes and metadata migration
  runtime/        durable runs + opaque canonical conversation-identity metadata
  actions.rs      canonical RunSpec → run_agent
  cli.rs          clap surface
  slash.rs        slash catalog
  session.rs      hybrid_run + hybrid_loop_run
  roles.rs        route_decision (conf/alt/fb)
  route_log.rs    route.jsonl audit
  init/           /init project scan → AGENTS.md
  gitops.rs       local git helpers
  agent/          cursor · grok · fm · abi · claude executors (argv.rs = per-backend grammars)
  memory/         trait + sqlite · wdbx + map · learned embedding providers/index
  mesh.rs         typed Unix bridge to ABI authenticated local multi-process proof
  hybrid_loop.rs  Gemma interpret → Max implement
  wdbx_bridge.rs  abbey wdbx → abi wdbx
  please_fix.rs  last-failure prompt + capture summarizer
  learn.rs        self-learn + review/stats
  models.rs       model aliases
  config.rs       config.toml (roles, memory_backend, backend, abi_bin)
  state.rs        per-cwd chats (read_chat_for takes the live backend)
  state/          canonical-first identity-mutation coordinator + private mirror journal
  tui/            7-tab ratatui app
tasks/            goals + todo board
docs/             identity · architecture · production
tests/
```
