// Ported from mlai `apps/mlai/lib/quasar-screens.tsx` (`QuasarSites`) at b6f3686.
import { Link } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { listSites } from "@/lib/quasar/api";
import type { Site } from "@/lib/quasar";
import { Notice, QuasarFrame, ServiceUnreachable, SiteStatusBadge } from "./shared";
import { errorText, formatDate, isUnreachable, useServiceOrigin } from "./util";

type State =
  { kind: "loading" } | { kind: "ready"; sites: Site[] } | { kind: "failed"; error: unknown };

export function QuasarSites() {
  const origin = useServiceOrigin();
  const [state, setState] = useState<State>({ kind: "loading" });

  // State is only set from the settled promise, so the effect below never
  // updates state synchronously.
  const fetchSites = useCallback(() => {
    listSites().then(
      (sites) => setState({ kind: "ready", sites }),
      (error: unknown) => setState({ kind: "failed", error }),
    );
  }, []);

  const load = useCallback(() => {
    setState({ kind: "loading" });
    fetchSites();
  }, [fetchSites]);

  // Reload whenever the configured origin changes (and once it is known): back
  // to "loading" during render, then fetch in the effect.
  const [prevOrigin, setPrevOrigin] = useState(origin);
  if (origin !== prevOrigin) {
    setPrevOrigin(origin);
    if (origin) setState({ kind: "loading" });
  }
  useEffect(() => {
    if (origin) fetchSites();
  }, [origin, fetchSites]);

  return (
    <QuasarFrame
      eyebrow="Quasar · local builder"
      title="Sites"
      lede="Next.js projects generated by the Quasar service on your machine. This list is read live from the service; nothing is stored by quesar.cloud."
    >
      <div className="mb-6 flex flex-wrap gap-3">
        <Button asChild>
          <Link to="/quasar/new">New site</Link>
        </Button>
        <Button
          type="button"
          variant="secondary"
          onClick={load}
          disabled={state.kind === "loading"}
        >
          Refresh
        </Button>
      </div>

      {state.kind === "loading" ? (
        <p className="text-sm text-fg-muted" aria-live="polite">
          Asking the service for its sites…
        </p>
      ) : null}

      {state.kind === "failed" ? (
        isUnreachable(state.error) ? (
          <ServiceUnreachable origin={origin} error={state.error} onRetry={load} />
        ) : (
          <Notice tone="error" title="The service refused the request">
            <p>{errorText(state.error)}</p>
          </Notice>
        )
      ) : null}

      {state.kind === "ready" && state.sites.length === 0 ? (
        <Notice title="No sites yet">
          <p>
            The service is running and holds no sites.{" "}
            <Link to="/quasar/new" className="text-accent">
              Create one from a prompt
            </Link>
            .
          </p>
        </Notice>
      ) : null}

      {state.kind === "ready" && state.sites.length > 0 ? (
        <ul className="grid gap-3 sm:grid-cols-2">
          {state.sites.map((site) => (
            <li key={site.id}>
              <Link
                to="/quasar/site/$id"
                params={{ id: site.id }}
                className="surface surface-hover block p-5 text-fg no-underline"
              >
                <div className="flex items-start justify-between gap-3">
                  <h2 className="font-display text-xl leading-tight">{site.name}</h2>
                  <SiteStatusBadge status={site.status} />
                </div>
                <p className="mt-1 font-mono text-xs text-fg-subtle">~/.quasar/sites/{site.slug}</p>
                <p className="mt-3 line-clamp-2 text-sm text-fg-muted">
                  {site.promptHistory.at(-1)?.prompt ?? "No prompt recorded."}
                </p>
                <p className="mt-3 text-xs text-fg-subtle">
                  Created {formatDate(site.createdAt)} · {site.promptHistory.length} prompt
                  {site.promptHistory.length === 1 ? "" : "s"}
                </p>
                {site.lastError ? (
                  <p className="mt-2 text-xs text-destructive">Last error: {site.lastError}</p>
                ) : null}
              </Link>
            </li>
          ))}
        </ul>
      ) : null}
    </QuasarFrame>
  );
}
