/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbbeyRouteImport } from './routes/abbey'
import { Route as AbbeyBotRouteImport } from './routes/abbey-bot'
import { Route as AbiRouteImport } from './routes/abi'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CellMachineRouteImport } from './routes/cell-machine'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FinancialModelRouteImport } from './routes/financial-model'
import { Route as GamaRouteImport } from './routes/gama'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuesarRouteImport } from './routes/quesar'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SkillCreatorRouteImport } from './routes/skill-creator'
import { Route as SourceRouteImport } from './routes/source'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TfPoseDemoRouteImport } from './routes/tf-pose-demo'
import { Route as WdbxRouteImport } from './routes/wdbx'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ConsoleWorkspaceRouteImport } from './routes/console.workspace'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ResearchSlugRouteImport } from './routes/research.$slug'
import { Route as ResearchImplementationsRouteImport } from './routes/research.implementations'
import { Route as ShowcaseAbbeyRouteImport } from './routes/showcase.abbey'
import { Route as ShowcaseDesignRouteImport } from './routes/showcase.design'
import { Route as ShowcaseExplainerRouteImport } from './routes/showcase.explainer'
import { Route as ShowcaseFilmRouteImport } from './routes/showcase.film'
import { Route as ShowcaseMegaRouteImport } from './routes/showcase.mega'
import { Route as ShowcaseTrailerRouteImport } from './routes/showcase.trailer'
import { Route as SourceNameRouteImport } from './routes/source.$name'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ResearchImplementationsSlugRouteImport } from './routes/research.implementations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbbeyRoute = AbbeyRouteImport.update({
  id: '/abbey',
  path: '/abbey',
  getParentRoute: () => rootRouteImport,
} as any)
const AbbeyBotRoute = AbbeyBotRouteImport.update({
  id: '/abbey-bot',
  path: '/abbey-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AbiRoute = AbiRouteImport.update({
  id: '/abi',
  path: '/abi',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CellMachineRoute = CellMachineRouteImport.update({
  id: '/cell-machine',
  path: '/cell-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialModelRoute = FinancialModelRouteImport.update({
  id: '/financial-model',
  path: '/financial-model',
  getParentRoute: () => rootRouteImport,
} as any)
const GamaRoute = GamaRouteImport.update({
  id: '/gama',
  path: '/gama',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuesarRoute = QuesarRouteImport.update({
  id: '/quesar',
  path: '/quesar',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillCreatorRoute = SkillCreatorRouteImport.update({
  id: '/skill-creator',
  path: '/skill-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TfPoseDemoRoute = TfPoseDemoRouteImport.update({
  id: '/tf-pose-demo',
  path: '/tf-pose-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const WdbxRoute = WdbxRouteImport.update({
  id: '/wdbx',
  path: '/wdbx',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ConsoleWorkspaceRoute = ConsoleWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ConsoleRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchImplementationsRoute = ResearchImplementationsRouteImport.update({
  id: '/implementations',
  path: '/implementations',
  getParentRoute: () => ResearchRoute,
} as any)
const ShowcaseAbbeyRoute = ShowcaseAbbeyRouteImport.update({
  id: '/abbey',
  path: '/abbey',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseDesignRoute = ShowcaseDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseExplainerRoute = ShowcaseExplainerRouteImport.update({
  id: '/explainer',
  path: '/explainer',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseFilmRoute = ShowcaseFilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseMegaRoute = ShowcaseMegaRouteImport.update({
  id: '/mega',
  path: '/mega',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseTrailerRoute = ShowcaseTrailerRouteImport.update({
  id: '/trailer',
  path: '/trailer',
  getParentRoute: () => ShowcaseRoute,
} as any)
const SourceNameRoute = SourceNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => SourceRoute,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchImplementationsSlugRoute =
  ResearchImplementationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ResearchImplementationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abbey': typeof AbbeyRoute
  '/abbey-bot': typeof AbbeyBotRoute
  '/abi': typeof AbiRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/blog': typeof BlogRouteWithChildren
  '/cell-machine': typeof CellMachineRoute
  '/changelog': typeof ChangelogRoute
  '/companion': typeof CompanionRoute
  '/company': typeof CompanyRoute
  '/console': typeof ConsoleRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/financial-model': typeof FinancialModelRoute
  '/gama': typeof GamaRoute
  '/get-started': typeof GetStartedRoute
  '/investors': typeof InvestorsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/platform': typeof PlatformRoute
  '/plugins': typeof PluginsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quesar': typeof QuesarRoute
  '/research': typeof ResearchRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/signup': typeof SignupRoute
  '/skill-creator': typeof SkillCreatorRoute
  '/source': typeof SourceRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/tf-pose-demo': typeof TfPoseDemoRoute
  '/wdbx': typeof WdbxRoute
  '/workspace': typeof WorkspaceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/console/workspace': typeof ConsoleWorkspaceRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/implementations': typeof ResearchImplementationsRouteWithChildren
  '/showcase/abbey': typeof ShowcaseAbbeyRoute
  '/showcase/design': typeof ShowcaseDesignRoute
  '/showcase/explainer': typeof ShowcaseExplainerRoute
  '/showcase/film': typeof ShowcaseFilmRoute
  '/showcase/mega': typeof ShowcaseMegaRoute
  '/showcase/trailer': typeof ShowcaseTrailerRoute
  '/source/$name': typeof SourceNameRoute
  '/team/$slug': typeof TeamSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/research/implementations/$slug': typeof ResearchImplementationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abbey': typeof AbbeyRoute
  '/abbey-bot': typeof AbbeyBotRoute
  '/abi': typeof AbiRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/blog': typeof BlogRouteWithChildren
  '/cell-machine': typeof CellMachineRoute
  '/changelog': typeof ChangelogRoute
  '/companion': typeof CompanionRoute
  '/company': typeof CompanyRoute
  '/console': typeof ConsoleRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/financial-model': typeof FinancialModelRoute
  '/gama': typeof GamaRoute
  '/get-started': typeof GetStartedRoute
  '/investors': typeof InvestorsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/platform': typeof PlatformRoute
  '/plugins': typeof PluginsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quesar': typeof QuesarRoute
  '/research': typeof ResearchRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/signup': typeof SignupRoute
  '/skill-creator': typeof SkillCreatorRoute
  '/source': typeof SourceRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/tf-pose-demo': typeof TfPoseDemoRoute
  '/wdbx': typeof WdbxRoute
  '/workspace': typeof WorkspaceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/console/workspace': typeof ConsoleWorkspaceRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/implementations': typeof ResearchImplementationsRouteWithChildren
  '/showcase/abbey': typeof ShowcaseAbbeyRoute
  '/showcase/design': typeof ShowcaseDesignRoute
  '/showcase/explainer': typeof ShowcaseExplainerRoute
  '/showcase/film': typeof ShowcaseFilmRoute
  '/showcase/mega': typeof ShowcaseMegaRoute
  '/showcase/trailer': typeof ShowcaseTrailerRoute
  '/source/$name': typeof SourceNameRoute
  '/team/$slug': typeof TeamSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/research/implementations/$slug': typeof ResearchImplementationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abbey': typeof AbbeyRoute
  '/abbey-bot': typeof AbbeyBotRoute
  '/abi': typeof AbiRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/architecture': typeof ArchitectureRoute
  '/benchmarks': typeof BenchmarksRoute
  '/blog': typeof BlogRouteWithChildren
  '/cell-machine': typeof CellMachineRoute
  '/changelog': typeof ChangelogRoute
  '/companion': typeof CompanionRoute
  '/company': typeof CompanyRoute
  '/console': typeof ConsoleRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRouteWithChildren
  '/financial-model': typeof FinancialModelRoute
  '/gama': typeof GamaRoute
  '/get-started': typeof GetStartedRoute
  '/investors': typeof InvestorsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/platform': typeof PlatformRoute
  '/plugins': typeof PluginsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quesar': typeof QuesarRoute
  '/research': typeof ResearchRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/signup': typeof SignupRoute
  '/skill-creator': typeof SkillCreatorRoute
  '/source': typeof SourceRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/tf-pose-demo': typeof TfPoseDemoRoute
  '/wdbx': typeof WdbxRoute
  '/workspace': typeof WorkspaceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/console/workspace': typeof ConsoleWorkspaceRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/implementations': typeof ResearchImplementationsRouteWithChildren
  '/showcase/abbey': typeof ShowcaseAbbeyRoute
  '/showcase/design': typeof ShowcaseDesignRoute
  '/showcase/explainer': typeof ShowcaseExplainerRoute
  '/showcase/film': typeof ShowcaseFilmRoute
  '/showcase/mega': typeof ShowcaseMegaRoute
  '/showcase/trailer': typeof ShowcaseTrailerRoute
  '/source/$name': typeof SourceNameRoute
  '/team/$slug': typeof TeamSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/research/implementations/$slug': typeof ResearchImplementationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abbey'
    | '/abbey-bot'
    | '/abi'
    | '/about'
    | '/apps'
    | '/architecture'
    | '/benchmarks'
    | '/blog'
    | '/cell-machine'
    | '/changelog'
    | '/companion'
    | '/company'
    | '/console'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/developers'
    | '/docs'
    | '/financial-model'
    | '/gama'
    | '/get-started'
    | '/investors'
    | '/links'
    | '/login'
    | '/mobile'
    | '/platform'
    | '/plugins'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/projects'
    | '/quesar'
    | '/research'
    | '/security'
    | '/services'
    | '/showcase'
    | '/signup'
    | '/skill-creator'
    | '/source'
    | '/team'
    | '/terms'
    | '/tf-pose-demo'
    | '/wdbx'
    | '/workspace'
    | '/blog/$slug'
    | '/console/workspace'
    | '/docs/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/research/$slug'
    | '/research/implementations'
    | '/showcase/abbey'
    | '/showcase/design'
    | '/showcase/explainer'
    | '/showcase/film'
    | '/showcase/mega'
    | '/showcase/trailer'
    | '/source/$name'
    | '/team/$slug'
    | '/api/auth/$'
    | '/research/implementations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abbey'
    | '/abbey-bot'
    | '/abi'
    | '/about'
    | '/apps'
    | '/architecture'
    | '/benchmarks'
    | '/blog'
    | '/cell-machine'
    | '/changelog'
    | '/companion'
    | '/company'
    | '/console'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/developers'
    | '/docs'
    | '/financial-model'
    | '/gama'
    | '/get-started'
    | '/investors'
    | '/links'
    | '/login'
    | '/mobile'
    | '/platform'
    | '/plugins'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/projects'
    | '/quesar'
    | '/research'
    | '/security'
    | '/services'
    | '/showcase'
    | '/signup'
    | '/skill-creator'
    | '/source'
    | '/team'
    | '/terms'
    | '/tf-pose-demo'
    | '/wdbx'
    | '/workspace'
    | '/blog/$slug'
    | '/console/workspace'
    | '/docs/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/research/$slug'
    | '/research/implementations'
    | '/showcase/abbey'
    | '/showcase/design'
    | '/showcase/explainer'
    | '/showcase/film'
    | '/showcase/mega'
    | '/showcase/trailer'
    | '/source/$name'
    | '/team/$slug'
    | '/api/auth/$'
    | '/research/implementations/$slug'
  id:
    | '__root__'
    | '/'
    | '/abbey'
    | '/abbey-bot'
    | '/abi'
    | '/about'
    | '/apps'
    | '/architecture'
    | '/benchmarks'
    | '/blog'
    | '/cell-machine'
    | '/changelog'
    | '/companion'
    | '/company'
    | '/console'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/developers'
    | '/docs'
    | '/financial-model'
    | '/gama'
    | '/get-started'
    | '/investors'
    | '/links'
    | '/login'
    | '/mobile'
    | '/platform'
    | '/plugins'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/projects'
    | '/quesar'
    | '/research'
    | '/security'
    | '/services'
    | '/showcase'
    | '/signup'
    | '/skill-creator'
    | '/source'
    | '/team'
    | '/terms'
    | '/tf-pose-demo'
    | '/wdbx'
    | '/workspace'
    | '/blog/$slug'
    | '/console/workspace'
    | '/docs/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/research/$slug'
    | '/research/implementations'
    | '/showcase/abbey'
    | '/showcase/design'
    | '/showcase/explainer'
    | '/showcase/film'
    | '/showcase/mega'
    | '/showcase/trailer'
    | '/source/$name'
    | '/team/$slug'
    | '/api/auth/$'
    | '/research/implementations/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbbeyRoute: typeof AbbeyRoute
  AbbeyBotRoute: typeof AbbeyBotRoute
  AbiRoute: typeof AbiRoute
  AboutRoute: typeof AboutRoute
  AppsRoute: typeof AppsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BenchmarksRoute: typeof BenchmarksRoute
  BlogRoute: typeof BlogRouteWithChildren
  CellMachineRoute: typeof CellMachineRoute
  ChangelogRoute: typeof ChangelogRoute
  CompanionRoute: typeof CompanionRoute
  CompanyRoute: typeof CompanyRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRouteWithChildren
  FinancialModelRoute: typeof FinancialModelRoute
  GamaRoute: typeof GamaRoute
  GetStartedRoute: typeof GetStartedRoute
  InvestorsRoute: typeof InvestorsRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  MobileRoute: typeof MobileRoute
  PlatformRoute: typeof PlatformRoute
  PluginsRoute: typeof PluginsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  QuesarRoute: typeof QuesarRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  SignupRoute: typeof SignupRoute
  SkillCreatorRoute: typeof SkillCreatorRoute
  SourceRoute: typeof SourceRouteWithChildren
  TeamRoute: typeof TeamRouteWithChildren
  TermsRoute: typeof TermsRoute
  TfPoseDemoRoute: typeof TfPoseDemoRoute
  WdbxRoute: typeof WdbxRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abbey': {
      id: '/abbey'
      path: '/abbey'
      fullPath: '/abbey'
      preLoaderRoute: typeof AbbeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abbey-bot': {
      id: '/abbey-bot'
      path: '/abbey-bot'
      fullPath: '/abbey-bot'
      preLoaderRoute: typeof AbbeyBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abi': {
      id: '/abi'
      path: '/abi'
      fullPath: '/abi'
      preLoaderRoute: typeof AbiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cell-machine': {
      id: '/cell-machine'
      path: '/cell-machine'
      fullPath: '/cell-machine'
      preLoaderRoute: typeof CellMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-model': {
      id: '/financial-model'
      path: '/financial-model'
      fullPath: '/financial-model'
      preLoaderRoute: typeof FinancialModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gama': {
      id: '/gama'
      path: '/gama'
      fullPath: '/gama'
      preLoaderRoute: typeof GamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quesar': {
      id: '/quesar'
      path: '/quesar'
      fullPath: '/quesar'
      preLoaderRoute: typeof QuesarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-creator': {
      id: '/skill-creator'
      path: '/skill-creator'
      fullPath: '/skill-creator'
      preLoaderRoute: typeof SkillCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tf-pose-demo': {
      id: '/tf-pose-demo'
      path: '/tf-pose-demo'
      fullPath: '/tf-pose-demo'
      preLoaderRoute: typeof TfPoseDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wdbx': {
      id: '/wdbx'
      path: '/wdbx'
      fullPath: '/wdbx'
      preLoaderRoute: typeof WdbxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/console/workspace': {
      id: '/console/workspace'
      path: '/workspace'
      fullPath: '/console/workspace'
      preLoaderRoute: typeof ConsoleWorkspaceRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/implementations': {
      id: '/research/implementations'
      path: '/implementations'
      fullPath: '/research/implementations'
      preLoaderRoute: typeof ResearchImplementationsRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/showcase/abbey': {
      id: '/showcase/abbey'
      path: '/abbey'
      fullPath: '/showcase/abbey'
      preLoaderRoute: typeof ShowcaseAbbeyRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/design': {
      id: '/showcase/design'
      path: '/design'
      fullPath: '/showcase/design'
      preLoaderRoute: typeof ShowcaseDesignRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/explainer': {
      id: '/showcase/explainer'
      path: '/explainer'
      fullPath: '/showcase/explainer'
      preLoaderRoute: typeof ShowcaseExplainerRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/film': {
      id: '/showcase/film'
      path: '/film'
      fullPath: '/showcase/film'
      preLoaderRoute: typeof ShowcaseFilmRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/mega': {
      id: '/showcase/mega'
      path: '/mega'
      fullPath: '/showcase/mega'
      preLoaderRoute: typeof ShowcaseMegaRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/trailer': {
      id: '/showcase/trailer'
      path: '/trailer'
      fullPath: '/showcase/trailer'
      preLoaderRoute: typeof ShowcaseTrailerRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/source/$name': {
      id: '/source/$name'
      path: '/$name'
      fullPath: '/source/$name'
      preLoaderRoute: typeof SourceNameRouteImport
      parentRoute: typeof SourceRoute
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof TeamRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/implementations/$slug': {
      id: '/research/implementations/$slug'
      path: '/$slug'
      fullPath: '/research/implementations/$slug'
      preLoaderRoute: typeof ResearchImplementationsSlugRouteImport
      parentRoute: typeof ResearchImplementationsRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ConsoleRouteChildren {
  ConsoleWorkspaceRoute: typeof ConsoleWorkspaceRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleWorkspaceRoute: ConsoleWorkspaceRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ResearchImplementationsRouteChildren {
  ResearchImplementationsSlugRoute: typeof ResearchImplementationsSlugRoute
}

const ResearchImplementationsRouteChildren: ResearchImplementationsRouteChildren =
  {
    ResearchImplementationsSlugRoute: ResearchImplementationsSlugRoute,
  }

const ResearchImplementationsRouteWithChildren =
  ResearchImplementationsRoute._addFileChildren(
    ResearchImplementationsRouteChildren,
  )

interface ResearchRouteChildren {
  ResearchSlugRoute: typeof ResearchSlugRoute
  ResearchImplementationsRoute: typeof ResearchImplementationsRouteWithChildren
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchSlugRoute: ResearchSlugRoute,
  ResearchImplementationsRoute: ResearchImplementationsRouteWithChildren,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

interface ShowcaseRouteChildren {
  ShowcaseAbbeyRoute: typeof ShowcaseAbbeyRoute
  ShowcaseDesignRoute: typeof ShowcaseDesignRoute
  ShowcaseExplainerRoute: typeof ShowcaseExplainerRoute
  ShowcaseFilmRoute: typeof ShowcaseFilmRoute
  ShowcaseMegaRoute: typeof ShowcaseMegaRoute
  ShowcaseTrailerRoute: typeof ShowcaseTrailerRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseAbbeyRoute: ShowcaseAbbeyRoute,
  ShowcaseDesignRoute: ShowcaseDesignRoute,
  ShowcaseExplainerRoute: ShowcaseExplainerRoute,
  ShowcaseFilmRoute: ShowcaseFilmRoute,
  ShowcaseMegaRoute: ShowcaseMegaRoute,
  ShowcaseTrailerRoute: ShowcaseTrailerRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

interface SourceRouteChildren {
  SourceNameRoute: typeof SourceNameRoute
}

const SourceRouteChildren: SourceRouteChildren = {
  SourceNameRoute: SourceNameRoute,
}

const SourceRouteWithChildren =
  SourceRoute._addFileChildren(SourceRouteChildren)

interface TeamRouteChildren {
  TeamSlugRoute: typeof TeamSlugRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamSlugRoute: TeamSlugRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbbeyRoute: AbbeyRoute,
  AbbeyBotRoute: AbbeyBotRoute,
  AbiRoute: AbiRoute,
  AboutRoute: AboutRoute,
  AppsRoute: AppsRoute,
  ArchitectureRoute: ArchitectureRoute,
  BenchmarksRoute: BenchmarksRoute,
  BlogRoute: BlogRouteWithChildren,
  CellMachineRoute: CellMachineRoute,
  ChangelogRoute: ChangelogRoute,
  CompanionRoute: CompanionRoute,
  CompanyRoute: CompanyRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRouteWithChildren,
  FinancialModelRoute: FinancialModelRoute,
  GamaRoute: GamaRoute,
  GetStartedRoute: GetStartedRoute,
  InvestorsRoute: InvestorsRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  MobileRoute: MobileRoute,
  PlatformRoute: PlatformRoute,
  PluginsRoute: PluginsRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  QuesarRoute: QuesarRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  SignupRoute: SignupRoute,
  SkillCreatorRoute: SkillCreatorRoute,
  SourceRoute: SourceRouteWithChildren,
  TeamRoute: TeamRouteWithChildren,
  TermsRoute: TermsRoute,
  TfPoseDemoRoute: TfPoseDemoRoute,
  WdbxRoute: WdbxRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
